CREATE TABLE users (
 id    SERIAL PRIMARY KEY,
 password TEXT NOT NULL,
 email TEXT NOT NULL UNIQUE CHECK(POSITION('@' IN email)>1),
 first_name VARCHAR (255) NOT NULL,
 last_name VARCHAR (255) NOT NULL,
 location VARCHAR (255) NOT NULL,
 date DATE NOT NULL DEFAULT CURRENT_DATE

);